// src/webserver/frontend/components/ListInput.vue
<style scoped lang="scss">
@import '../css/style';


.br-list-input {
  display: flex;
  flex-direction: column;
  align-items: stretch;
  user-select: none;
  width: 100%;

  &.disabled {
    pointer-events: none;
    opacity: 50%;
    cursor: default;
  }

  .br-list-item {
    @include row;
    margin-bottom: 8px;
    width: 100%;

    .button {
      margin-left: 8px;
    }
  }

  & > .button {
    margin-bottom: 8px;
  }
}

</style>

<template>
  <div :class="['br-list-input', {
    disabled,
  }]">
    <div v-for="(v, i) in value || []" class="br-list-item" :key="i">
      <br-input v-if="['string', 'password', 'number'].includes(type)"
        :value="value[i]"
        @input="val => updateItem(i, val)"
        :placeholder="placeholder ? placeholder.toString() : ''"
        :type="type"
      />
      <br-dropdown v-if="type === 'enum'"
        :value="value[i]"
        :options="options"
        @input="val => updateItem(i, val)"
      />
      <br-role-dropdown v-if="type === 'role'"
        :value="value[i]"
        @input="val => updateItem(i, val)"
      />
      <br-button icon warn
        data-tooltip="Remove this item from the list"
        @click="removeItem(i)">
        <MinusIcon/>
      </br-button>
    </div>
    <br-button icon main
      data-tooltip="Add an item to the list"
      @click="addItem()">
      <PlusIcon/>
    </br-button>
  </div>
</template>
<script>

import Vue from 'vue';

import PlusIcon from 'vue-tabler-icons/icons/PlusIcon';
import MinusIcon from 'vue-tabler-icons/icons/MinusIcon';

export default Vue.component('br-list-input', {
  components: {
    PlusIcon, MinusIcon,
  },
  methods: {
    updateItem(index, val) {
      const clone = this.value.slice();
      clone[index] = val;
      this.$emit('input', clone);
    },
    addItem() {
      const clone = this.value.slice();
      clone.push({string: '', number: 0, password: '', enum: this.options && this.options[0]}[this.type]);
      this.$emit('input', clone);
    },
    removeItem(index) {
      const clone = this.value.slice();
      clone.splice(index, 1);
      this.$emit('input', clone);
    }
  },
  props: {
    placeholder: String,
    disabled: Boolean,
    type: String,
    value: Array,
    options: Array,
  },
});

</script>

// frontend/src/components/list-input/index.tsx
import { IconMinus, IconPlus } from '@tabler/icons-react';
import { Button } from '../button';
import { Dropdown } from '../dropdown';
import { Input } from '../input';
import { RoleDropdown } from '../role-dropdown';

export type ListInputType = 'string' | 'password' | 'number' | 'enum' | 'role';

export const ListInput = ({
  placeholder = '',
  disabled = false,
  type,
  value = [],
  options = [],
  onChange,
}: {
  placeholder?: string;
  disabled?: boolean;
  type: ListInputType;
  value: any[];
  options?: any[];
  onChange: (value: any[]) => void;
}) => {
  const updateItem = (index: number, val: any) => {
    const clone = value.slice();
    clone[index] = val;
    onChange(clone);
  };

  const addItem = () => {
    const clone = value.slice();
    clone.push(
      {
        string: '',
        number: 0,
        password: '',
        role: '',
        enum: options && options[0],
      }[type],
    );
    onChange(clone);
  };

  const removeItem = (index: number) => {
    const clone = value.slice();
    clone.splice(index, 1);
    onChange(clone);
  };

  return (
    <div className={`br-list-input ${disabled ? 'disabled' : ''}`}>
      {(value || []).map((v, i) => (
        <div className="br-list-item" key={i}>
          {(type === 'string' || type === 'password' || type === 'number') && (
            <Input
              value={v}
              onChange={v => updateItem(i, v)}
              placeholder={placeholder}
              type={type === 'string' ? 'text' : type}
              disabled={disabled}
            />
          )}
          {type === 'enum' && (
            <Dropdown
              value={v}
              options={options}
              onChange={val => updateItem(i, val)}
              disabled={disabled}
            />
          )}
          {type === 'role' && (
            <RoleDropdown
              value={v}
              onChange={val => updateItem(i, val)}
              disabled={disabled}
            />
          )}
          <Button
            icon
            warn
            data-tooltip="Remove this item from the list"
            onClick={() => removeItem(i)}
            disabled={disabled}
          >
            <IconMinus />
          </Button>
        </div>
      ))}
      <Button
        icon
        main
        data-tooltip="Add an item to the list"
        onClick={addItem}
        disabled={disabled}
      >
        <IconPlus />
      </Button>
    </div>
  );
};
