// frontend/src/components/infinite-scroll/index.tsx
import React, { useEffect, useRef, useState } from 'react';

export const InfiniteScroll = ({
  loading,
  offset = 0,
  onTopScrollsToBottom = true,
  onBottom,
  onTop,
  children,
}: {
  loading: boolean;
  offset?: number;
  onTopScrollsToBottom?: boolean;
  onBottom: () => void;
  onTop: () => void;
  children: React.ReactNode;
}) => {
  const [scrollPosition, setScrollPosition] = useState(0);
  const [lastDirection, setLastDirection] = useState('');
  const targetRef = useRef<HTMLDivElement>(null);

  const emitEvents = (name: 'bottom' | 'top') => {
    if (!loading) {
      setLastDirection(name);
      name === 'bottom' ? onBottom() : onTop();
    }
  };

  const handleElementScroll = (e: React.UIEvent<HTMLDivElement>) => {
    const target = e.currentTarget;
    const currentScrollPosition = target.scrollTop;

    if (
      currentScrollPosition > scrollPosition &&
      currentScrollPosition + target.offsetHeight >=
        target.scrollHeight - offset
    ) {
      emitEvents('bottom');
    } else if (
      currentScrollPosition < scrollPosition &&
      currentScrollPosition <= offset
    ) {
      emitEvents('top');
    }

    setScrollPosition(currentScrollPosition);
  };

  useEffect(() => {
    if (
      onTopScrollsToBottom &&
      !loading &&
      lastDirection === 'top' &&
      targetRef.current
    ) {
      targetRef.current.scrollTo({
        top:
          targetRef.current.scrollHeight -
          targetRef.current.offsetHeight -
          offset -
          2,
        behavior: 'instant',
      });
    }
  }, [loading, lastDirection, onTopScrollsToBottom, offset]);

  return (
    <div ref={targetRef} onScroll={handleElementScroll}>
      {children}
    </div>
  );
};

// src/webserver/frontend/components/InfiniteScroll.vue
<template>
  <div @scroll="handleElementScroll">
    <slot/>
  </div>
</template>

<script>
import Vue from 'vue';
export default Vue.component('v-infinite-scroll', {
  props: {
    loading: {type: Boolean},
    offset: {type: Number, default: 0},
    onTopScrollsToBottom: {type: Boolean, default: true}
  },
  data () {
    return {
      target: null,
      scrollPosition: 0,
      lastDirection: ''
    }
  },
  methods: {
    handleElementScroll: function(e) {
      if (!this.target) this.target = e.target
      let currentScrollPosition = e.target.scrollTop
      if (currentScrollPosition > this.scrollPosition && currentScrollPosition + e.target.offsetHeight >= e.target.scrollHeight - this.offset) {
        this.emitEvents('bottom');
      } else if (currentScrollPosition < this.scrollPosition && currentScrollPosition <= this.offset) {
        this.emitEvents('top');
      }
      this.scrollPosition = currentScrollPosition;
    },
    emitEvents (name) {
      if (!this.loading) {
        this.lastDirection = name;
        this.$emit(name);
      }
    }
  },
  watch: {
    loading () {
      if (this.onTopScrollsToBottom && !this.loading && this.lastDirection == 'top') {
        this.target.scroll({
          top: this.target.scrollHeight - this.target.offsetHeight - this.offset - 2,
          behavior: 'instant',
        });
      }
    }
  }
});
</script>
