// frontend/src/views/server/index.tsx
import {
  IconCheck,
  IconPlayerPlay,
  IconPlayerStop,
  IconRefresh,
  IconX,
} from '@tabler/icons-react';
import { useCallback, useEffect, useState } from 'react';
import type { IStoreAutoRestartConfig } from '../../../../src/webserver/backend/types';
import { Button } from '../../components/button';
import { Dimmer } from '../../components/dimmer';
import { Footer } from '../../components/footer';
import { Header } from '../../components/header';
import { Input } from '../../components/input';
import { Modal } from '../../components/modal';
import { NavHeader } from '../../components/navbar';
import { Page, PageContent } from '../../components/page';
import { PopoutContent } from '../../components/popout';
import { SideNav } from '../../components/sidenav';
import { Toggle } from '../../components/toggle';
import { SavedSpan, SavedStatus, useSaved } from '../../hooks/useSaved';
import { rpcNotify, rpcReq } from '../../socket';
import {
  restartServer,
  startServer,
  stopServer,
  useServerLiveness,
} from '../../stores/liveness';

export const ServerView = () => {
  const {
    started,
    stopping,
    starting,
    loading: statusLoading,
  } = useServerLiveness();
  const [confirm, setConfim] = useState({
    show: false,
    message: '',
    resolve: (_val: boolean) => {},
  });
  const prompt = useCallback(
    (message: string) =>
      new Promise(resolve => {
        setConfim({
          message,
          show: true,
          resolve(val) {
            resolve(val);
            setConfim({ show: false, message: '', resolve: () => {} });
          },
        });
      }),
    []
  );

  const [config, setConfig] = useState<IStoreAutoRestartConfig | null>(null);

  useEffect(() => {
    rpcReq('server.autorestart.get').then(setConfig);
  }, []);

  const saveConfig = useCallback(async () => {
    if (!config) return;

    const blob = {
      type: 'autoRestartConfig',
      maxUptime: Math.round(Math.max(1, Math.min(config.maxUptime, 168))),
      maxUptimeEnabled: config.maxUptimeEnabled,
      emptyUptime: Math.round(Math.max(1, Math.min(config.emptyUptime, 168))),
      emptyUptimeEnabled: config.emptyUptimeEnabled,
      dailyHour: Math.round(Math.max(0, Math.min(config.dailyHour, 23))),
      dailyHourEnabled: config.dailyHourEnabled,
      announcementEnabled: config.announcementEnabled,
      bricksEnabled: config.bricksEnabled,
      playersEnabled: config.playersEnabled,
      minigamesEnabled: config.minigamesEnabled,
      environmentEnabled: config.environmentEnabled,
    };
    rpcNotify('server.autorestart.set', blob);
  }, [config]);

  const saved = useSaved(saveConfig);

  const changeConfig = <K extends keyof IStoreAutoRestartConfig>(name: K) => {
    return (value: IStoreAutoRestartConfig[K]) => {
      if (!config) return;
      config[name] = value;
      saved.fire();
    };
  };

  return (
    <Page>
      <NavHeader title="Server" />
      <PageContent>
        <SideNav />
        <div className="generic-container server-container">
          <Header>
            Server Status:{' '}
            {starting
              ? 'starting'
              : stopping
              ? 'stopping'
              : started
              ? 'started'
              : 'stopped'}
          </Header>
          <div className="buttons">
            <Button
              main
              data-tooltip="Start the server"
              disabled={starting || stopping || statusLoading || started}
              onClick={() =>
                prompt('start the server').then(ok => ok && startServer())
              }
            >
              <IconPlayerPlay />
              Start
            </Button>
            <Button
              error
              data-tooltip="Stop the server"
              disabled={starting || stopping || statusLoading || started}
              onClick={() =>
                prompt('stop the server').then(ok => ok && stopServer())
              }
            >
              <IconPlayerStop />
              Stop
            </Button>
            <Button
              warn
              data-tooltip="Stop the server if it's running, then start the server. Saves minigames/environment/bricks if enabled below."
              disabled={starting || stopping || statusLoading || started}
              onClick={() =>
                prompt('restart the server').then(ok => ok && restartServer())
              }
            >
              <IconRefresh />
              Restart
            </Button>
          </div>
          <Header style={{ marginTop: 8 }}>
            Auto Restart
            <SavedSpan show={saved.status === SavedStatus.Waiting} />
          </Header>
          {config && (
            <div className="inputs-list">
              <div
                className="inputs-item"
                data-tooltip="How many hours before restarting regardless of online players"
              >
                <label>Max Server Uptime (Hours)</label>
                <div className="inputs">
                  <Toggle
                    tooltip="Enabled"
                    value={config.maxUptimeEnabled}
                    onChange={changeConfig('maxUptimeEnabled')}
                  />
                  <Input
                    type="number"
                    placeholder="Hours"
                    tooltip="Uptime Hours"
                    value={config.maxUptime}
                    onChange={changeConfig('maxUptime')}
                  />
                </div>
              </div>
              <div
                className="inputs-item"
                data-tooltip="How many hours before restarting when no players are online"
              >
                <label>Empty Server Lifetime (Hours)</label>
                <div className="inputs">
                  <Toggle
                    tooltip="Enabled"
                    value={config.emptyUptimeEnabled}
                    onChange={changeConfig('emptyUptimeEnabled')}
                  />
                  <Input
                    type="number"
                    placeholder="Hours"
                    tooltip="Uptime Hours"
                    value={config.emptyUptime}
                    onChange={changeConfig('emptyUptime')}
                  />
                </div>
              </div>
              <div
                className="inputs-item"
                data-tooltip="Restart every day at a certain hour"
              >
                <label>Daily at a Specific Hour</label>
                <div className="inputs">
                  <Toggle
                    tooltip="Enabled"
                    value={config.dailyHourEnabled}
                    onChange={changeConfig('dailyHourEnabled')}
                  />
                  <Input
                    type="number"
                    placeholder="Hour"
                    tooltip="Hour (0 = 12am, 13 = 1pm)"
                    value={config.dailyHour}
                    onChange={changeConfig('dailyHour')}
                  />
                </div>
              </div>
              <div
                className="inputs-item"
                data-tooltip="When enabled, announces auto restart"
              >
                <label>Restart Announcement</label>
                <div className="inputs">
                  <Toggle
                    tooltip="Enabled"
                    value={config.announcementEnabled}
                    onChange={changeConfig('announcementEnabled')}
                  />
                </div>
              </div>
              <div
                className="inputs-item"
                data-tooltip="When enabled, reconnects players at their previous positions"
              >
                <label>Reload Players</label>
                <div className="inputs">
                  <Toggle
                    tooltip="Enabled"
                    value={config.playersEnabled}
                    onChange={changeConfig('playersEnabled')}
                  />
                </div>
              </div>
              <div
                className="inputs-item"
                data-tooltip="When enabled, saves and re-loads bricks on autorestart"
              >
                <label>Reload Bricks</label>
                <div className="inputs">
                  <Toggle
                    tooltip="Enabled"
                    value={config.bricksEnabled}
                    onChange={changeConfig('bricksEnabled')}
                  />
                </div>
              </div>
              <div
                className="inputs-item"
                data-tooltip="When enabled, saves and re-loads minigames on autorestart"
              >
                <label>Reload Minigames</label>
                <div className="inputs">
                  <Toggle
                    tooltip="Enabled"
                    value={config.minigamesEnabled}
                    onChange={changeConfig('minigamesEnabled')}
                  />
                </div>
              </div>
              <div
                className="inputs-item"
                data-tooltip="When enabled, saves and re-loads environment on autorestart"
              >
                <label>Reload Environment</label>
                <div className="inputs">
                  <Toggle
                    tooltip="Enabled"
                    value={config.environmentEnabled}
                    onChange={changeConfig('environmentEnabled')}
                  />
                </div>
              </div>
            </div>
          )}
          <Dimmer visible={confirm.show}>
            <Modal visible>
              <Header> Confirmation </Header>
              <PopoutContent>
                <p>Are you sure you want to {confirm.message}?</p>
              </PopoutContent>
              <Footer>
                <Button main onClick={() => confirm.resolve(true)}>
                  <IconCheck />
                  Yes
                </Button>
                <div style={{ flex: 1 }} />
                <Button normal onClick={() => confirm.resolve(false)}>
                  <IconX />
                  No
                </Button>
              </Footer>
            </Modal>
          </Dimmer>
        </div>
      </PageContent>
    </Page>
  );
};

// src/webserver/frontend/views/Server.vue
<style lang="scss" scoped>
@import '../css/style';

.server-container {
  display: flex;
  align-items: stretch;
  flex-direction: column;
}

.buttons {
  flex-direction: row;
  display: flex;
  margin-top: 8px;
}
</style>

<template>
  <page>
    <nav-header title="Server"> </nav-header>
    <page-content>
      <side-nav :active="$route.name" />
      <div class="generic-container server-container">
        <br-header
          >Server Status:
          {{
            starting
              ? 'starting'
              : stopping
              ? 'stopping'
              : started
              ? 'started'
              : 'stopped'
          }}</br-header
        >
        <div class="buttons">
          <br-button
            main
            data-tooltip="Start the server"
            :disabled="starting || stopping || loading || started"
            @click="start()"
          >
            <PlayerPlayIcon />
            Start
          </br-button>
          <br-button
            error
            data-tooltip="Stop the server"
            :disabled="starting || stopping || loading || !started"
            @click="stop()"
          >
            <PlayerStopIcon />
            Stop
          </br-button>
          <br-button
            warn
            data-tooltip="Stop the server if it's running, then start the server. Saves minigames/environment/bricks if enabled below."
            :disabled="starting || stopping || loading"
            @click="restart()"
          >
            <RefreshIcon />
            Restart
          </br-button>
        </div>
        <br-header style="margin-top: 8px">Auto Restart</br-header>
        <div class="inputs-list">
          <div
            class="inputs-item"
            data-tooltip="How many hours before restarting regardless of online players"
          >
            <label>Max Server Uptime (Hours)</label>
            <div class="inputs">
              <br-toggle
                tooltip="Enabled"
                v-model="maxUptimeEnabled"
                @input="sendConfig"
              />
              <br-input
                type="number"
                placeholder="Hours"
                tooltip="Uptime Hours"
                v-model="maxUptime"
                @input="sendConfig"
              />
            </div>
          </div>
          <div
            class="inputs-item"
            data-tooltip="How many hours before restarting when no players are online"
          >
            <label>Empty Server Lifetime (Hours)</label>
            <div class="inputs">
              <br-toggle
                tooltip="Enabled"
                v-model="emptyUptimeEnabled"
                @input="sendConfig"
              />
              <br-input
                type="number"
                placeholder="Hours"
                tooltip="Uptime Hours"
                v-model="emptyUptime"
                @input="sendConfig"
              />
            </div>
          </div>
          <div
            class="inputs-item"
            data-tooltip="Restart every day at a certain hour"
          >
            <label>Daily at a Specific Hour</label>
            <div class="inputs">
              <br-toggle
                tooltip="Enabled"
                v-model="dailyHourEnabled"
                @input="sendConfig"
              />
              <br-input
                type="number"
                placeholder="Hour"
                tooltip="Hour (0 = 12am, 13 = 1pm)"
                v-model="dailyHour"
                @input="sendConfig"
              />
            </div>
          </div>
          <div
            class="inputs-item"
            data-tooltip="When enabled, announces auto restart"
          >
            <label>Restart Announcement</label>
            <div class="inputs">
              <br-toggle
                tooltip="Enabled"
                v-model="announcementEnabled"
                @input="sendConfig"
              />
            </div>
          </div>
          <div
            class="inputs-item"
            data-tooltip="When enabled, reconnects players at their previous positions"
          >
            <label>Reload Players</label>
            <div class="inputs">
              <br-toggle
                tooltip="Enabled"
                v-model="playersEnabled"
                @input="sendConfig"
              />
            </div>
          </div>
          <div
            class="inputs-item"
            data-tooltip="When enabled, saves and re-loads bricks on autorestart"
          >
            <label>Reload Bricks</label>
            <div class="inputs">
              <br-toggle
                tooltip="Enabled"
                v-model="bricksEnabled"
                @input="sendConfig"
              />
            </div>
          </div>
          <div
            class="inputs-item"
            data-tooltip="When enabled, saves and re-loads minigames on autorestart"
          >
            <label>Reload Minigames</label>
            <div class="inputs">
              <br-toggle
                tooltip="Enabled"
                v-model="minigamesEnabled"
                @input="sendConfig"
              />
            </div>
          </div>
          <div
            class="inputs-item"
            data-tooltip="When enabled, saves and re-loads environment on autorestart"
          >
            <label>Reload Environment</label>
            <div class="inputs">
              <br-toggle
                tooltip="Enabled"
                v-model="environmentEnabled"
                @input="sendConfig"
              />
            </div>
          </div>
        </div>
        <br-dimmer :visible="showConfirm">
          <br-modal visible>
            <br-header> Confirmation </br-header>
            <br-popout-content>
              <p>Are you sure you want to {{ message }}?</p>
            </br-popout-content>
            <br-footer>
              <br-button main @click="resolve(true)">
                <CheckIcon />
                Yes
              </br-button>
              <div style="flex: 1" />
              <br-button normal @click="resolve(false)">
                <XIcon />No
              </br-button>
            </br-footer>
          </br-modal>
        </br-dimmer>
      </div>
    </page-content>
  </page>
</template>

<script>
import PlayerStopIcon from 'vue-tabler-icons/icons/PlayerStopIcon';
import PlayerPlayIcon from 'vue-tabler-icons/icons/PlayerPlayIcon';
import RefreshIcon from 'vue-tabler-icons/icons/RefreshIcon';
import XIcon from 'vue-tabler-icons/icons/XIcon';
import CheckIcon from 'vue-tabler-icons/icons/CheckIcon';

export default {
  components: { PlayerStopIcon, PlayerPlayIcon, RefreshIcon, CheckIcon, XIcon },
  created() {
    this.getStatus();
  },
  beforeDestroy() {
    this.$$emit('unsubscribe', 'server');
  },
  destroyed() {},
  mounted() {},
  methods: {
    async start() {
      if (!(await this.prompt('start the server'))) return;
      this.$$request('server.start');
    },
    async stop() {
      if (!(await this.prompt('stop the server'))) return;
      this.$$request('server.stop');
    },
    async restart() {
      if (!(await this.prompt('restart the server'))) return;
      this.loading = true;
      this.$$request('server.restart');
    },
    async prompt(message) {
      this.showConfirm = true;
      this.message = message;
      return await new Promise(resolve => {
        this.resolve = val => {
          this.showConfirm = false;
          resolve(val);
        };
      });
    },
    sendConfig() {
      const config = {
        type: 'autoRestartConfig',
        maxUptime: Math.round(Math.max(1, Math.min(this.maxUptime, 168))),
        maxUptimeEnabled: this.maxUptimeEnabled,
        emptyUptime: Math.round(Math.max(1, Math.min(this.emptyUptime, 168))),
        emptyUptimeEnabled: this.emptyUptimeEnabled,
        dailyHour: Math.round(Math.max(0, Math.min(this.dailyHour, 24))),
        dailyHourEnabled: this.dailyHourEnabled,
        announcementEnabled: this.announcementEnabled,
        bricksEnabled: this.bricksEnabled,
        playersEnabled: this.playersEnabled,
        minigamesEnabled: this.minigamesEnabled,
        environmentEnabled: this.environmentEnabled,
      };
      this.$$notify('server.autorestart.set', config);
      this.$forceUpdate();
    },
    async getStatus() {
      this.$$emit('subscribe', 'server');
      this.loading = true;
      const { started, starting, stopping } = await this.$$request(
        'server.started'
      );
      this.started = started;
      this.starting = starting;
      this.stopping = stopping;
      const config = await this.$$request('server.autorestart.get');
      for (const key in config) {
        if (key in this) {
          this[key] = config[key];
        }
      }
      this.loading = false;
    },
  },
  sockets: {
    // watch server status
    status({ started, starting, stopping }) {
      this.started = started;
      this.starting = starting;
      this.stopping = stopping;
      this.loading = false;
    },
    connect() {
      this.getStatus();
    },
  },
  computed: {},
  data() {
    return {
      loading: true,
      started: false,
      starting: false,
      stopping: false,
      message: '',
      showConfirm: false,
      resolve: undefined,

      maxUptime: 48,
      maxUptimeEnabled: true,
      emptyUptime: 24,
      emptyUptimeEnabled: true,
      dailyHour: 2,
      dailyHourEnabled: false,
      announcementEnabled: true,
      bricksEnabled: true,
      playersEnabled: true,
      minigamesEnabled: true,
      environmentEnabled: true,
    };
  },
};
</script>
