// src/webserver/frontend/views/Home.vue
<style lang="scss">
@import '../css/style';

.grid-container {
  position: relative;
  max-height: calc(100vh - 24px * 2 - 8px * 2 - 113px);
  width: 100%;
  overflow-y: scroll;
  overflow-x: hidden;
  z-index: 10;
}

.vue-grid-layout {
  position: absolute;
  left: 0;
  margin-top: -8px;
  top: 0;
  width: 100%;
  height: 100%;
}

.vue-grid-item:not(.vue-grid-placeholder) {
  background-color: $br-element-popout-bg;
}
.vue-grid-item .resizing {
  opacity: 0.9;
}

.vue-grid-item {
  display: flex;
  flex-direction: column;
}

.vue-draggable-dragging .drag-handle {
  background-color: $br-element-footer-bg;
}

.vue-resizable-handle {
  opacity: 0;
}

.resize-handle {
  color: $br-boring-button-fg;
  font-size: 24px;
  position: absolute;
  right: -4px;
  bottom: -4px;
}

.disable-userselect {
}

.vue-grid-item.vue-grid-placeholder {
  background-color: $br-button-normal !important;
}

.drag-contents {
  position: relative;
  display: flex;
  align-items: stretch;
  flex: 1;
}

.widgets-container {
  z-index: 100;
  display: flex;
  flex-direction: column;
  align-items: flex-end;

  .widgets-list {
    background-color: $br-element-footer-bg;
    margin-right: 8px;
    min-width: 200px;

    .widget-item {
      background-color: $br-bg-primary;
      display: flex;
      align-items: center;
      justify-content: space-between;
      height: 50px;
      padding: 0 10px;

      &:nth-child(even) {
        background-color: $br-bg-primary-alt;
      }

      .name {
        text-transform: uppercase;
        display: flex;
        align-items: center;

        .icon {
          margin-right: 10px;
        }
      }
    }
  }
}



@media screen and (max-width: 600px) {
  .vue-grid-layout {
    margin: -8px;
    width: calc(100% + 16px);
  }

  .grid-container {
    margin-top: 0;
    max-height: none;
    overflow: hidden;
  }
}

</style>

<template>
  <page :loading="loading">
    <nav-header title="Dashboard">
      <div class="widgets-container">
        <br-button normal boxy
          data-tooltip="Add more widgets to the dashboard"
          @click="showWidgets = !showWidgets"
        >
          <AppsIcon />
          Widgets
        </br-button>
        <div class="widgets-list" :style="{display: showWidgets ? 'block' : 'none'}">
          <div v-for="widget, k in widgetList" :key="k" class="widget-item">
            <div class="name" :data-tooltip="widget.tooltip">
              <component :is="widget.icon"/>
              {{k}}
            </div>
            <br-button main icon v-if="!hasWidget[k]"
              :data-tooltip="'Add '+k+' widget'"
              @click="addWidget(k)"
            >
              <PlusIcon/>
            </br-button>
            <br-button warn icon v-else
              :data-tooltip="'Remove '+k+' widget'"
              @click="removeWidget(k)"
            >
              <MinusIcon/>
            </br-button>
          </div>
        </div>
      </div>
    </nav-header>
    <page-content>
      <side-nav :active="$route.name" />
      <div class="grid-container">
        <grid-layout
          :layout="layout"
          :colNum="5"
          :row-height="100"
          :is-draggable="true"
          :is-resizable="true"
          :vertical-compact="false"
          :margin="[8, 8]"
          :responsive="true"
          :use-css-transforms="true"
          @layout-updated="layoutUpdated"
        >
          <grid-item v-for="item in layout"
           :x="item.x"
           :y="item.y"
           :w="item.w"
           :h="item.h"
           :i="item.i"
           :key="item.i"
           :minW="2"
           :maxW="10"
           :minH="2"
           :maxH="10"
           drag-allow-from=".drag-handle"
           drag-ignore-from=".no-drag"
          >
            <br-header class="drag-handle">
              <span style="flex: 1">{{item.i}}</span>
              <br-button icon error class="no-drag"
                data-tooltip="Close widget"
                @click="removeWidget(item.i)"
              >
                <XIcon />
              </br-button>
            </br-header>
            <div class="drag-contents">
              <component v-if="item.component" :is="item.component"></component>
            </div>
            <ChevronDownRightIcon class="resize-handle" />
          </grid-item>
        </grid-layout>
      </div>
    </page-content>
  </page>
</template>

<script>

import { GridLayout, GridItem } from 'vue-grid-layout';

import AppsIcon from 'vue-tabler-icons/icons/AppsIcon';
import PlusIcon from 'vue-tabler-icons/icons/PlusIcon';
import MinusIcon from 'vue-tabler-icons/icons/MinusIcon';
import MessageDotsIcon from 'vue-tabler-icons/icons/MessageDotsIcon';
import ListIcon from 'vue-tabler-icons/icons/ListIcon';
import XIcon from 'vue-tabler-icons/icons/XIcon';
import ChevronDownRightIcon from 'vue-tabler-icons/icons/ChevronDownRightIcon';

export default {
  created() {

  },
  methods: {
    layoutUpdated(layout) {
      localStorage.omeggaDashLayout = JSON.stringify(layout);
    },
    removeWidget(id) {
      this.layout = this.layout.filter(l => l.i !== id);
    },
    addWidget(id) {
      this.layout.push({
        x: 0, y: 0,
        w: 2, h: 2,
        i: id,
        component: this.widgetList[id].component,
      });
    },
  },
  sockets: {
  },
  computed: {
    hasWidget() {
      return Object.fromEntries(this.layout.map(l => [l.i, true]));
    },
  },
  data() {
    // default layout
    let layout = [
      {x: 0, y: 0, w: 2, h: 2, i: 'chat', component: 'br-chat-widget'},
      {x: 2, y: 0, w: 2, h: 2, i: 'status', component: 'br-status-widget'},
    ];

    if (localStorage.omeggaDashLayout) {
      layout = JSON.parse(localStorage.omeggaDashLayout);
    }

    /* this.$route.name */
    return {
      loading: false,
      showWidgets: false,
      widgetList: {
        chat: {
          component: 'br-chat-widget',
          icon: 'MessageDotsIcon',
          tooltip: 'Chat with online players',
        },
        status: {
          component: 'br-status-widget',
          icon: 'ListIcon',
          tooltip: 'View current online players and server status',
        },
      },
      layout,
    };
  },
  components: {
    AppsIcon, PlusIcon, MinusIcon, MessageDotsIcon, ListIcon, XIcon, ChevronDownRightIcon,
    GridLayout,
    GridItem,
  },
};

</script>

// frontend/src/views/home/index.tsx
import { Button, Header, NavHeader, PageContent, SideNav } from '@components';
import {
  IconApps,
  IconChevronDownRight,
  IconList,
  IconMessageDots,
  IconMinus,
  IconPlus,
  IconX,
} from '@tabler/icons-react';
import { useEffect, useState } from 'react';
import GridLayout, { type Layout } from 'react-grid-layout';
import { ChatWidget, StatusWidget } from '../../widgets';

const WIDGET_LIST = {
  chat: {
    component: ChatWidget,
    icon: IconMessageDots,
    tooltip: 'Chat with online players',
  },
  status: {
    component: StatusWidget,
    icon: IconList,
    tooltip: 'View current online players and server status',
  },
};
const DEFAULT_LAYOUT = [
  { x: 0, y: 0, w: 2, h: 2, i: 'chat' },
  { x: 2, y: 0, w: 2, h: 2, i: 'status' },
] satisfies Layout[];

export const HomeView = () => {
  const [layout, setLayout] = useState<Layout[]>(() => {
    if (localStorage.omeggaDashLayout2) {
      try {
        return JSON.parse(localStorage.omeggaDashLayout2);
      } catch (err) {
        console.error(
          'Invalid layout in localStorage, using default layout',
          err
        );
        return DEFAULT_LAYOUT;
      }
    }
    return DEFAULT_LAYOUT;
  });
  useEffect(() => {
    localStorage.omeggaDashLayout2 = JSON.stringify(layout);
  }, [layout]);

  const removeWidget = (widget: string) => {
    setLayout(layout.filter(w => w.i !== widget));
  };

  const addWidget = (widget: string) => {
    if (!(widget in WIDGET_LIST)) return;
    setLayout([
      ...layout,
      {
        x: 0,
        y: 0,
        w: 2,
        h: 2,
        i: widget,
      },
    ]);
  };

  const [showWidgets, setShowWidgets] = useState(true);
  const hasWidget = Object.fromEntries(layout.map(w => [w.i, true]));

  return (
    <>
      <NavHeader title="Dashboard">
        <div className="widgets-container">
          <Button
            normal
            boxy
            data-tooltip="Add more widgets to the dashboard"
            onClick={() => setShowWidgets(!showWidgets)}
          >
            <IconApps />
            Widgets
          </Button>
          <div
            className="widgets-list"
            style={{ display: showWidgets ? 'block' : 'none' }}
          >
            {Object.entries(WIDGET_LIST).map(([k, widget]) => (
              <div key={k} className="widget-item">
                <div className="name" data-tooltip={widget.tooltip}>
                  <widget.icon />
                  {k}
                </div>
                {hasWidget[k] ? (
                  <Button
                    warn
                    icon
                    data-tooltip={`Remove ${k} widget`}
                    onClick={() => removeWidget(k)}
                  >
                    <IconMinus />
                  </Button>
                ) : (
                  <Button
                    main
                    icon
                    data-tooltip={`Add ${k} widget`}
                    onClick={() => addWidget(k)}
                  >
                    <IconPlus />
                  </Button>
                )}
              </div>
            ))}
          </div>
        </div>
      </NavHeader>
      <PageContent>
        <SideNav />
        <div className="grid-container">
          <GridLayout
            layout={layout}
            cols={5}
            rowHeight={100}
            isDraggable
            isResizable
            verticalCompact={false}
            margin={[8, 8]}
            useCSSTransforms
            onLayoutChange={newLayout => setLayout(newLayout)}
            draggableHandle=".drag-handle"
            draggableCancel=".no-drag"
            resizeHandle={() => (
              <IconChevronDownRight className="resize-handle" />
            )}
          >
            {layout.map(item => {
              const Component =
                WIDGET_LIST[item.i as keyof typeof WIDGET_LIST]!.component;
              return (
                <div
                  key={item.i}
                  data-grid={{ minW: 2, maxW: 10, minH: 2, maxH: 10 }}
                >
                  <Header className="drag-handle">
                    <span style={{ flex: 1 }}>{item.i}</span>
                    <Button
                      icon
                      error
                      className="no-drag"
                      data-tooltip="Close widget"
                      onClick={() => removeWidget(item.i)}
                    >
                      <IconX />
                    </Button>
                  </Header>
                  <div className="drag-contents">
                    <Component />
                  </div>
                </div>
              );
            })}
          </GridLayout>
        </div>
      </PageContent>
    </>
  );
};
