// src/webserver/frontend/components/ChatTime.vue
<style scoped>
.chat-timestamp {
  align-self: center;
  font-size: 16px;
  margin-right: 8px;
  font-weight: bold;
  text-align: right;
  width: 75px;
  min-width: 75px;
  color: #ccc;
}

</style>

<template>
  <span class="chat-timestamp">
    {{hours}}:{{minutes}}{{pm}}
  </span>
</template>
<script>

import Vue from 'vue';

export default Vue.component('chat-time', {
  props: ['time'],
  created() {
    const date = new Date(this.time);
    this.hours = date.getHours();
    this.pm = this.hours > 12 ? 'pm' : 'am';
    if (this.hours > 12) {
      this.hours -= 12;
    } else if (this.hours === 0) {
      this.hours = 12;
    }
    this.minutes = (date.getMinutes() + '').padStart(2, '0');
  },
});

</script>

// frontend/src/components/chat-time/index.tsx
export const ChatTime = ({ time }: { time: string | number | Date }) => {
  const date = new Date(time);
  let hours = date.getHours();
  const pm = hours >= 12 ? 'PM' : 'AM';
  if (hours > 12) {
    hours -= 12;
  } else if (hours === 0) {
    hours = 12;
  }
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return (
    <div className="chat-timestamp">
      {hours}:{minutes} {pm}
    </div>
  );
};
