// frontend/src/widgets/chat/index.tsx
import { Button, Footer, Input, Scroll } from '@components';
import type { IStoreChat } from '@omegga/webserver/backend/types';
import { IconSend } from '@tabler/icons-react';
import Linkify from 'linkify-react';
import React, { useEffect, useRef, useState } from 'react';
import { ioEmit, rpcNotify, rpcReq, socket } from '../../socket';

type ChatEntry = IStoreChat & {
  _id: string;
  createdAt?: Date;
  updatedAt?: Date;
};

export const ChatWidget = () => {
  const [chats, setChats] = useState<ChatEntry[]>([]);
  const [message, setMessage] = useState('');
  const ref = useRef<HTMLDivElement | null>(null);

  const scrollToBottom = () => {
    if (ref.current) {
      ref.current.scrollTop = ref.current.scrollHeight;
    }
  };

  useEffect(() => {
    const handleChat = (log: ChatEntry) => {
      setChats(prevChats => {
        const updatedChats = [...prevChats, log];
        return updatedChats.length > 50
          ? updatedChats.slice(updatedChats.length - 50)
          : updatedChats;
      });
      scrollToBottom();
    };

    socket.on('chat', handleChat);
    ioEmit('subscribe', 'chat');
    rpcReq('chat.recent').then((logs: ChatEntry[]) => {
      setChats(logs.reverse());
      scrollToBottom();
    });

    return () => {
      socket.off('chat', handleChat);
      ioEmit('unsubscribe', 'chat');
    };
  }, []);

  const sendMessage = (event: React.FormEvent) => {
    event.preventDefault();

    if (message.length > 140 || message.length === 0) return;

    // Mock notification
    rpcNotify('chat', message);
    setMessage('');
  };

  return (
    <div className="chat-widget">
      <Scroll className="messages">
        <div className="messages-child">
          {chats.map(log => (
            <div key={log._id} className="log-entry">
              {log.action === 'msg' && (
                <div className="chat-message">
                  {log.user?.web ? '[' : ''}
                  <span style={{ color: `#${log.user?.color}` }}>
                    {log.user?.name}
                  </span>
                  {log.user?.web ? ']' : ''}:{' '}
                  <Linkify as="span">{log.message}</Linkify>
                </div>
              )}
              {log.action === 'leave' && (
                <div className="join-message">
                  <span>{log.user?.name}</span> left the game.
                </div>
              )}
              {log.action === 'join' && (
                <div className="join-message">
                  <span>{log.user?.name}</span> joined the game
                  {log.user?.isFirst ? ' for the first time' : ''}.
                </div>
              )}
              {log.action === 'server' && (
                <Linkify as="div" className="server-message">
                  {log.message}
                </Linkify>
              )}
            </div>
          ))}
        </div>
      </Scroll>
      <form onSubmit={sendMessage}>
        <Footer>
          <Input
            type="text"
            placeholder="Message"
            value={message}
            onChange={v => setMessage(v)}
          />
          <Button
            normal
            icon
            style={{ marginLeft: '10px' }}
            onClick={sendMessage}
          >
            <IconSend />
          </Button>
        </Footer>
      </form>
    </div>
  );
};

// src/webserver/frontend/widgets/Chat.vue
<style lang="scss">
@import '../css/style';

.chat-widget {
  display: flex;
  flex: 1;
  flex-direction: column;
  position: relative;
  align-items: stretch;
  max-width: 100%;

  .messages {
    flex: 1;
    position: relative;

    .messages-child {
      @include column;
      margin: 8px;
    }
  }

  .input {
    flex: 1;
    width: calc(100% - 24px - 20px);
  }
}

</style>

<template>
  <div class="chat-widget">
    <br-scroll class="messages">
      <div class="messages-child">
        <div v-for="log in chats" :key="log._id" class="log-entry">
          <div v-if="log.action === 'msg'" class="chat-message">
            {{log.user.web ? '[' : ''}}<span class="user" :style="{color: '#'+log.user.color}"
            >{{log.user.name}}</span>{{log.user.web ? ']' : ''}}: {{log.message}}
          </div>
          <div v-if="log.action === 'leave'" class="join-message">
            <span class="user">{{log.user.name}}</span> left the game.
          </div>
          <div v-if="log.action === 'join'" class="join-message">
            <span class="user">{{log.user.name}}</span> joined the game{{log.user.isFirst ? ' for the first time' : ''}}.
          </div>
          <div v-if="log.action === 'server'" class="server-message">
            {{log.message}}
          </div>
        </div>
      </div>
    </br-scroll>
    <form @submit="sendMessage">
      <br-footer>
        <br-input type="text" placeholder="Message" v-model="message" />
        <br-button normal icon style="margin-left: 10px" @click="sendMessage">
          <SendIcon />
        </br-button>
      </br-footer>
    </form>
  </div>
</template>
<script>

import Vue from 'vue';
import SendIcon from 'vue-tabler-icons/icons/SendIcon';


export default Vue.component('br-chat-widget', {
  components: { SendIcon },
  sockets: {
    chat(log) {
      this.chats.push(log);

      // if the log is too long - remove the excess messages (you should probably be in the history view)
      if (this.chats.length > 50)
        this.chats.splice(0, 50 - this.chats.length);

      this.scroll();
    },
    connect() {
      this.getChats();
    },
  },
  beforeDestroy() {
    this.$$emit('unsubscribe', 'chat');
  },
  created() {
    this.getChats();
  },
  methods: {
    getChats() {
      this.$$emit('subscribe', 'chat');
      this.$$request('chat.recent').then(logs => {
        this.chats = logs.reverse();
        this.scroll();
      });
    },
    scroll() {
      // scroll to bottom of message log
      window.requestAnimationFrame(() => {
        const container = this.$el.querySelector('.scroll-scroller');
        container.scrollTop = container.scrollHeight;
      });
    },
    // send message from form
    sendMessage(event) {
      event.preventDefault();

      if (this.message.length > 140 || this.message.length === 0)
        return;

      this.$$notify('chat', this.message);
      this.message = '';
    },
  },
  data() {
    return {
      chats: [],
      message: '',
    }
  },
});

</script>
